import { ArrowLeft, Pencil, RefreshCw, Trash2 } from 'lucide-react'
import { formatCurrency, formatDate } from '../../../lib/format'
import { LOTTERY_STATUS_LABELS, LOTTERY_TYPE_LABELS } from '../constants'
import { LOTTERY_MARKET_LABELS, getPendingUiLabel } from '../lottery-schedule'
import type { LotteryEntry } from '../types'
import { NumberChip } from './NumberChip'

export const LotteryEntryDetail = ({ entry, onClose, onEdit, onResult, onDelete }: { entry: LotteryEntry; onClose: () => void; onEdit: () => void; onResult: () => void; onDelete: () => void }) => {
  const net = Number(entry.payout) - Number(entry.stake)
  return <div className="fixed inset-0 z-[55] flex items-end justify-center bg-slate-950/40"><section className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-[2rem] bg-white p-5"><header className="flex items-center gap-3"><button type="button" onClick={onClose} className="grid size-10 place-items-center rounded-full bg-slate-100"><ArrowLeft className="size-5" /></button><div><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Bản ghi</p><h2 className="text-xl font-black">Chi tiết lô đề</h2></div></header><div className="mt-6"><div className="flex items-center justify-between"><span className="rounded-lg bg-violet-100 px-3 py-1.5 text-xs font-black text-violet-800">{LOTTERY_TYPE_LABELS[entry.play_type]}</span><span className="text-xs font-black text-slate-500">{entry.status === 'pending' ? getPendingUiLabel(entry.draw_date,entry.draw_time) : LOTTERY_STATUS_LABELS[entry.status]}</span></div><h3 className="mt-5 text-lg font-black text-slate-900">{LOTTERY_MARKET_LABELS[entry.market]}{entry.market === 'south'||entry.market === 'central'||entry.market === 'north' ? ` · ${entry.station}` : ''}</h3><p className="mt-1 text-xs font-bold text-violet-600">{formatDate(entry.draw_date)} · Xổ lúc {entry.draw_time}{entry.market === 'hcm_vip' ? ' · ALL' : ''}</p><div className="mt-5"><p className="mb-2 text-xs font-bold text-slate-400">Các số</p><div className="flex flex-wrap gap-2">{entry.numbers.map((number)=><NumberChip key={number} number={number} hit={(entry.hit_numbers??[]).includes(number)} />)}</div></div><div className="mt-6 grid grid-cols-3 gap-2 border-y border-slate-100 py-4 text-xs"><div><p className="text-slate-400">Tiền vào</p><p className="mt-1 font-black">{formatCurrency(Number(entry.stake))}</p></div><div><p className="text-slate-400">Tiền nhận</p><p className="mt-1 font-black">{formatCurrency(Number(entry.payout))}</p></div><div><p className="text-slate-400">Chênh lệch</p><p className={`mt-1 font-black ${net>=0?'text-emerald-700':'text-red-600'}`}>{net>0?'+':''}{formatCurrency(net)}</p></div></div>{entry.note&&<div className="mt-4"><p className="text-xs text-slate-400">Ghi chú</p><p className="mt-1 text-sm font-semibold text-slate-700">{entry.note}</p></div>}<button type="button" onClick={onResult} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 text-sm font-black text-white"><RefreshCw className="size-4" /> Cập nhật kết quả</button><button type="button" onClick={onEdit} className="mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-slate-100 text-xs font-black text-slate-600"><Pencil className="size-4" /> Chỉnh sửa</button><button type="button" onClick={onDelete} className="mt-2 flex h-10 w-full items-center justify-center gap-2 text-xs font-black text-red-600"><Trash2 className="size-4" /> Xóa bản ghi</button></div></section></div>
}
